fix failure parsing -Infinity on buffer boundary
In cases where a -Infinity value gets split due to a buffer
boundary an exception was thrown indicating an invalid numeric
value. With the test case added to TestNumericValues I get an
exception:

```
testParsingOfLongerSequencesWithNonNumeric(com.fasterxml.jackson.core.json.TestNumericValues)  Time elapsed: 5.306 sec  <<< ERROR!
com.fasterxml.jackson.core.JsonParseException: Invalid numeric value: Missing integer part (next char 'I' (code 73))
 at [Source: java.io.StringReader@164b3e4f; line: 1, column: 50690]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1501)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:522)
	at com.fasterxml.jackson.core.base.ParserBase.reportInvalidNumber(ParserBase.java:1025)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseNumber2(ReaderBasedJsonParser.java:1050)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseNegNumber(ReaderBasedJsonParser.java:964)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:668)
	at com.fasterxml.jackson.core.json.TestNumericValues.testParsingOfLongerSequencesWithNonNumeric(TestNumericValues.java:470)
```

I don't know if it is the best fix or not, but it was fairly
easy to fix the problem I was seeing by changing ReaderBasedJsonParser
to call `_handleInvalidNumberStart` instead of `reportInvalidNumber`.